import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Components/Navbar/Navbar'
import Footer from './Components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'pti',
  description: 'Generated by create pti',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      
      <body className={inter.className}>
        <div className='font-[Poppins] bg-gray-200 '>
        <Navbar/>
          <div className="pt-[30px] "> {children}</div>
         <Footer/>
        </div>
       </body>
      
    </html>
  )
}
